// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remoting_api.proto

package com.hyf.cloudnative.remoting.mesh.proxy.grpc.generate;

public final class RemotingApiProto {
  private RemotingApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_remoting_v1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_remoting_v1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_remoting_v1_Message_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_remoting_v1_Message_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022remoting_api.proto\022\013remoting.v1\032\031googl" +
      "e/protobuf/any.proto\"\234\002\n\007Message\022\n\n\002id\030\001" +
      " \001(\005\022\013\n\003req\030\002 \001(\010\022\r\n\005event\030\003 \001(\010\022\022\n\nclas" +
      "s_name\030\004 \001(\014\022\023\n\013method_name\030\005 \001(\014\022\026\n\016arg" +
      "_class_name\030\006 \001(\014\022\032\n\022payload_class_name\030" +
      "\007 \001(\014\022%\n\007payload\030\010 \001(\0132\024.google.protobuf" +
      ".Any\0224\n\010metadata\030\t \003(\0132\".remoting.v1.Mes" +
      "sage.MetadataEntry\032/\n\rMetadataEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012\200\001\n\013Remoting" +
      "Api\0225\n\007Request\022\024.remoting.v1.Message\032\024.r" +
      "emoting.v1.Message\022:\n\010BiStream\022\024.remotin" +
      "g.v1.Message\032\024.remoting.v1.Message(\0010\001BK" +
      "\n5com.hyf.cloudnative.remoting.mesh.prox" +
      "y.grpc.generateB\020RemotingApiProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_remoting_v1_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_remoting_v1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_remoting_v1_Message_descriptor,
        new String[] { "Id", "Req", "Event", "ClassName", "MethodName", "ArgClassName", "PayloadClassName", "Payload", "Metadata", });
    internal_static_remoting_v1_Message_MetadataEntry_descriptor =
      internal_static_remoting_v1_Message_descriptor.getNestedTypes().get(0);
    internal_static_remoting_v1_Message_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_remoting_v1_Message_MetadataEntry_descriptor,
        new String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
